version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  nosql.data:
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port

  rabbitmqservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${MICROSERVICES_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${MICROSERVICES_SERVICE_BUS_USERNAME}
      - EventBusPassword=${MICROSERVICES_SERVICE_BUS_PASSWORD}
      - SubscriptionClientName=rmqservice
    ports:
      - "5101:80"   # Important: In a production environment your should remove the external port (5101) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  service1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${MICROSERVICES_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${MICROSERVICES_SERVICE_BUS_USERNAME}
      - EventBusPassword=${MICROSERVICES_SERVICE_BUS_PASSWORD}
      - SubscriptionClientName=service1
    ports:
      - "5102:80"   # Important: In a production environment your should remove the external port (5102) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  mongoservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${MICROSERVICES_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${MICROSERVICES_SERVICE_BUS_USERNAME}
      - EventBusPassword=${MICROSERVICES_SERVICE_BUS_PASSWORD}
      - SubscriptionClientName=mongoservice
      - MongoConnectionString=${MICROSERVICES_AZURE_COSMOSDB:-mongodb://nosql.data}
      - MongoDatabase=MessagingDb
    ports:
      - "5103:80"   # Important: In a production environment your should remove the external port (5102) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).
